export const CoffeeInfo = [
  {
    name: "Americano",
    calory: 10,
    suga: 0,
    protein: 1,
    sodium: 5,
    sat_fat: 0,
    caffeine: 150,
    description: "아메리카노는 에스프레소의 진한 풍미를 잘 느낄 수 있는 커피입니다.",
  },
  {
    name: "Cappuccino",
    calory: 110,
    sugar: 8,
    protein: 6,
    sodium: 70,
    sat_fat: 3,
    caffeine: 75,
    description:"풍부하고 진한 에스프레소에 신선한 우유와 우유 거품이 들어간 커피입니다.",
  },
  {
    name: "Latte",
    calory: 180,
    sugar: 13,
    protein: 10,
    sodium: 115,
    sat_fat: 5,
    caffeine: 75,
    description:"진한 에스프레소가 신선한 스팀 밀크를 만나 부드러워진 커피 위에 우유 거품을 살짝 얹은 카페 라떼입니다.",
  },
  {
    name: "Mocha",
    calory: 290,
    sugar: 25,
    protein: 10,
    sodium: 105,
    sat_fat: 9,
    caffeine: 95,
    description:"진한 에스프레소와 초콜릿 맛이 어우러진 휘핑크림으로 마무리한 커피입니다.",
  },
  {
    name: "Espresso",
    calory: 5,
    sugar: 0,
    protein: 0,
    sodium: 0,
    sat_fat: 0,
    caffeine: 75,
    description:"고압,고온의 물로 커피를 추출하는 가장 기본적인 커피입니다.",
  }
]